# Generated by Django 4.0.4 on 2022-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='efforts',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working')], default=1, max_length=7),
        ),
    ]
